#!/usr/bin/env bash
#
# mayhem/build.sh — build pForth: the in-process libFuzzer harness, its standalone
# reproducer, AND the project's own test-suite binary.
#
# pForth builds via platforms/unix/Makefile:
#   pforth            = bootstrap interpreter (compiled from C)
#   pforth.dic        = dictionary built by running pforth over fth/system.fth
#   pfdicdat.h        = dictionary image header (embedded when PF_STATIC_DIC)
#   pforth_standalone = final interpreter with the dictionary embedded
#
# The fuzz TARGET is NOT the CLI binary — the raw CLI (`pforth_standalone @@`) could not be
# instrumented by Mayhem (0 edges). Instead we compile an in-process libFuzzer harness
# (mayhem/pforth_fuzzer.c) that calls pfInitialize()/pfInterpretText()/pfTerminate() over the
# same interpreter code path, linked against the embedded-dictionary (PF_STATIC_DIC) objects.
#
# Builds performed:
#   1) TEST build  — project's normal flags → mayhem/out/pforth_standalone_test (for test.sh)
#   2) pfdicdat.h  — generated by the bootstrap interpreter (needed by the PF_STATIC_DIC build)
#   3) FUZZ build  — every embedded object (minus pf_main.o, which carries main()) instrumented
#      with $SANITIZER_FLAGS + coverage + -DPF_NO_FILEIO (neuters file words so untrusted Forth
#      source cannot touch the real filesystem — see mayhem/pforth_fuzzer.c), linked with the
#      libFuzzer engine → /mayhem/pforth_fuzzer
#   4) STANDALONE  — same objects + harness linked against $STANDALONE_FUZZ_MAIN → /mayhem/pforth_fuzzer-standalone
#   5) TWIN        — a second compile of the same sources and harness with the FUZZ build's compile
#      line plus ONE flag, -fsanitize-recover=undefined, linked with the libFuzzer engine →
#      mayhem/out/pforth_fuzzer_twin. For mayhem/test.sh only (never at /mayhem, not a Mayhem
#      target): the DO +LOOP and 1+/1- wrap-around tests reach real signed overflows that stop the
#      graded binary, so they run on this twin, which reports the overflow and keeps going.
#   3), 4) and 5) also link mayhem/lsan_off.cc, the build-time __lsan_is_turned_off() hook (SPEC.md
#   §6.2 item 15): leak detection is off, ASan's memory-error checks and UBSan stay fully on.
#
# The harness has no timer or watchdog. An unconditional loop (e.g. `: L BEGIN AGAIN ; L`) is
# bounded by the runner: libFuzzer's -timeout / the Mayhemfile `timeout:`. See the harness header.
set -euo pipefail

[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${STANDALONE_FUZZ_MAIN:=/opt/mayhem/StandaloneFuzzTargetMain.c}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${COVERAGE_FLAGS=}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE STANDALONE_FUZZ_MAIN MAYHEM_JOBS COVERAGE_FLAGS

cd "$SRC"
UNIXDIR="$SRC/platforms/unix"
CSRC="$SRC/csrc"
mkdir -p "$SRC/mayhem/out"

# 1) TEST build: project's NORMAL flags (independent of the sanitized build) so mayhem/test.sh
#    only RUNS the suite. COVERAGE_FLAGS (empty by default) instruments it for coverage measurement.
make -C "$UNIXDIR" clean
make -C "$UNIXDIR" -j"$MAYHEM_JOBS" all CC="$CC" \
    EXTRA_CCOPTS="$COVERAGE_FLAGS" XLDFLAGS="$COVERAGE_FLAGS"
cp "$UNIXDIR/pforth_standalone" "$SRC/mayhem/out/pforth_standalone_test"

# 2) Generate pfdicdat.h (the embedded static dictionary) using the freshly-built bootstrap
#    interpreter. `make pfdicdat` leaves pfdicdat.h in $UNIXDIR. The bootstrap is unsanitized (the
#    dictionary image is interpreter output, not code under test).
#
#    Deterministic dictionary addresses: SDAD (fth/savedicd.fth) dumps the bootstrap's raw
#    dictionary memory, and some cells in it hold absolute addresses from the bootstrap process:
#    RAND-SEED (fth/misc2.fth: `variable rand-seed here rand-seed !`), HLD, leftover USTACK
#    entries and the private history KH-ADDRESS. A normal PIE+malloc bootstrap gets new ASLR
#    addresses on every run, so each rebuild of identical source baked different values into
#    pfdicdat.h. Forth code does arithmetic on these cells, not just loads: the first RANDOM /
#    CHOOSE results changed, and `0 0 #> TYPE` (which reads the stale HLD) could crash on one
#    build and pass on another. ASLR cannot be turned off here (Docker's default seccomp blocks
#    `setarch -R`), and the generated header must not be edited by hand. Instead this step
#    builds the bootstrap non-PIE with pForth's own static pool allocator (PF_NO_MALLOC,
#    csrc/pf_mem.c; one of the options the Makefile lists), so the dictionary lives in .bss at a
#    link-time address that is the same on every build. XCPPFLAGS repeats the Makefile default
#    ($(FPOPTS) -D_DEFAULT_SOURCE -D_GNU_SOURCE) and adds the pool options. The pool is 16 MiB to
#    leave headroom (the default is 1 MiB).
#    Only this generator is affected. The fuzz and standalone objects in steps 3-4 are separate
#    compiles with the normal allocator, PIE and full ASan+UBSan, and the dictionary contents are
#    the same apart from those address cells. The baked addresses are now small constants, which
#    are unmapped in the PIE fuzz binaries, so a stale dictionary pointer faults the same way on
#    every rebuild. One remaining varying cell is SDAD's own FILE* (SDAD-BUFFER-FID, from the brk
#    heap). It is harmless: the fuzz build's file words are PF_NO_FILEIO stubs.
make -C "$UNIXDIR" clean
make -C "$UNIXDIR" -j"$MAYHEM_JOBS" pfdicdat CC="$CC" \
    XCPPFLAGS="-DPF_SUPPORT_FP -D_DEFAULT_SOURCE -D_GNU_SOURCE -DPF_NO_MALLOC -DPF_MEM_POOL_SIZE=0x1000000" \
    EXTRA_CCOPTS="-fno-pie" XLDFLAGS="-no-pie"
test -f "$UNIXDIR/pfdicdat.h"

# 3) FUZZ build. Compile every pForth translation unit that the embedded (PF_STATIC_DIC) build
#    uses — EXCEPT pf_main.c, whose main() would clash with the libFuzzer/standalone driver —
#    with $SANITIZER_FLAGS, DWARF-3 debug info, and libFuzzer coverage. Flags mirror the
#    Makefile's embedded compile (EMBCCOPTS=-DPF_STATIC_DIC, FPOPTS=-DPF_SUPPORT_FP).
#    -DPF_NO_FILEIO additionally swaps in pForth's own safe stub file-I/O backend (csrc/pf_io.c) so
#    OPEN-FILE/CREATE-FILE/DELETE-FILE/WRITE-FILE/READ-FILE/(RENAME-FILE)/INCLUDE-FILE become no-ops
#    that return a failure code without touching the real filesystem — untrusted Forth source fed to
#    the fuzz/standalone binaries cannot read, write, create or delete anything in the container.
#    This is FUZZ-BUILD ONLY: the TEST build above (step 1) keeps real file I/O so t_file.fth still
#    exercises the genuine POSIX file-I/O backend.
PF_SRCS=(
    "$CSRC/pf_cglue.c" "$CSRC/pf_clib.c" "$CSRC/pf_core.c" "$CSRC/pf_inner.c"
    "$CSRC/pf_io.c" "$CSRC/pf_io_none.c" "$CSRC/pf_mem.c" "$CSRC/pf_save.c"
    "$CSRC/pf_text.c" "$CSRC/pf_words.c" "$CSRC/pfcompil.c" "$CSRC/pfcustom.c"
    "$CSRC/paging/pagedmem.c" "$CSRC/paging/lockpage.c" "$CSRC/paging/qadmpage.c"
    "$CSRC/posix/pf_io_posix.c" "$CSRC/stdio/pf_fileio_stdio.c"
)

# Compile flags: -x c so clang treats the (extension-correct) sources as C; PF_STATIC_DIC embeds
# the dictionary; PF_SUPPORT_FP matches the default float build; -I$UNIXDIR puts the generated
# pfdicdat.h on the include path (pf_save.c does #include "pfdicdat.h"); -I$CSRC for the headers.
CFLAGS_COMMON=(
    -x c -O1 -DPF_STATIC_DIC -DPF_SUPPORT_FP -DPF_NO_FILEIO -D_DEFAULT_SOURCE -D_GNU_SOURCE
    -I"$UNIXDIR" -I"$CSRC"
    $SANITIZER_FLAGS $DEBUG_FLAGS
)

OBJDIR="$SRC/mayhem/obj"
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"
objs=()
for src in "${PF_SRCS[@]}"; do
    obj="$OBJDIR/$(echo "$src" | sed "s#$SRC/##; s#/#_#g").o"
    "$CC" "${CFLAGS_COMMON[@]}" -fsanitize=fuzzer-no-link -c "$src" -o "$obj"
    objs+=("$obj")
done

# Harness object (also needs the embedded-dictionary defines + include paths).
"$CC" "${CFLAGS_COMMON[@]}" -fsanitize=fuzzer-no-link \
    -c "$SRC/mayhem/pforth_fuzzer.c" -o "$OBJDIR/pforth_fuzzer.o"

# Build-time LeakSanitizer off-switch (mayhem/lsan_off.cc, SPEC.md §6.2 item 15), compiled with
# $SANITIZER_FLAGS and linked into BOTH binaries below. Only leak detection is affected.
"$CXX" $SANITIZER_FLAGS $DEBUG_FLAGS -c "$SRC/mayhem/lsan_off.cc" -o "$OBJDIR/lsan_off.o"

# Link the libFuzzer target.
"$CC" $SANITIZER_FLAGS $DEBUG_FLAGS $LIB_FUZZING_ENGINE \
    "$OBJDIR/pforth_fuzzer.o" "$OBJDIR/lsan_off.o" "${objs[@]}" -lm -o /mayhem/pforth_fuzzer

# 4) STANDALONE reproducer: same objects + harness, linked against the run-once driver instead of
#    the libFuzzer engine (one input file, natural crash, no libFuzzer runtime).
"$CC" $SANITIZER_FLAGS $DEBUG_FLAGS -c "$STANDALONE_FUZZ_MAIN" -o "$OBJDIR/standalone_main.o"
"$CC" $SANITIZER_FLAGS $DEBUG_FLAGS \
    "$OBJDIR/standalone_main.o" "$OBJDIR/pforth_fuzzer.o" "$OBJDIR/lsan_off.o" "${objs[@]}" -lm \
    -o /mayhem/pforth_fuzzer-standalone

# 5) TWIN for mayhem/test.sh: the FUZZ build's compile line (CFLAGS_COMMON: same -O1, defines,
#    $SANITIZER_FLAGS and debug flags; fuzzer-no-link) with only -fsanitize-recover=undefined added,
#    so UBSan prints its report and continues instead of aborting. ASan is unchanged (it still
#    aborts), no runtime options are set, and the binary is linked with the libFuzzer engine like
#    /mayhem/pforth_fuzzer. test.sh runs pForth's DO +LOOP and 1+/1- wrap-around tests on it: they
#    hit real signed overflows (csrc/pf_inner.c) that stop the graded binary, and without this twin
#    they would run only on the normal-flags test binary, so a patch that changes that code only in
#    the fuzz build would go unseen. The objects are compiled in parallel; this adds a few seconds.
TWINDIR="$SRC/mayhem/obj-twin"
rm -rf "$TWINDIR"; mkdir -p "$TWINDIR"
twin_objs=() pids=()
for src in "${PF_SRCS[@]}" "$SRC/mayhem/pforth_fuzzer.c"; do
    obj="$TWINDIR/$(echo "$src" | sed "s#$SRC/##; s#/#_#g").o"
    "$CC" "${CFLAGS_COMMON[@]}" -fsanitize-recover=undefined -fsanitize=fuzzer-no-link \
        -c "$src" -o "$obj" &
    pids+=("$!"); twin_objs+=("$obj")
done
for pid in "${pids[@]}"; do wait "$pid"; done
"$CC" $SANITIZER_FLAGS -fsanitize-recover=undefined $DEBUG_FLAGS $LIB_FUZZING_ENGINE \
    "${twin_objs[@]}" "$OBJDIR/lsan_off.o" -lm -o "$SRC/mayhem/out/pforth_fuzzer_twin"

ls -l /mayhem/pforth_fuzzer /mayhem/pforth_fuzzer-standalone "$SRC/mayhem/out/pforth_standalone_test" \
    "$SRC/mayhem/out/pforth_fuzzer_twin"
